# Generated by Django 3.1.2 on 2020-10-29 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='candidate_id',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='question_id',
        ),
        migrations.AddField(
            model_name='polls',
            name='answer_boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='polls',
            name='answer_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='candidate_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='question_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_boolean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polls'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_text',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polls'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polls'),
        ),
    ]
