# Generated by Django 3.1.2 on 2020-10-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201028_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer_boolean',
        ),
        migrations.AddField(
            model_name='answers',
            name='answer_boolean',
            field=models.ManyToManyField(to='polls.Polls'),
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='email',
        ),
        migrations.AddField(
            model_name='candidates',
            name='email',
            field=models.ManyToManyField(to='polls.Polls'),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_text',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_text',
            field=models.ManyToManyField(to='polls.Polls'),
        ),
    ]
