# Generated by Django 3.1.2 on 2020-10-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201028_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='answers',
            name='answer_text',
            field=models.ManyToManyField(related_name='_answers_answer_text_+', to='polls.Polls'),
        ),
    ]
