# Generated by Django 3.1.2 on 2020-10-30 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201028_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.RenameField(
            model_name='polls',
            old_name='answer_id',
            new_name='answers_id',
        ),
        migrations.RenameField(
            model_name='polls',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='polls',
            old_name='author_email',
            new_name='email_creator',
        ),
        migrations.RenameField(
            model_name='polls',
            old_name='question_text',
            new_name='question_id',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_boolean',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='dni_ci',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='author',
        ),
        migrations.AddField(
            model_name='answers',
            name='candidate',
            field=models.ManyToManyField(null=True, to='polls.Candidates', verbose_name='Candidato'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='phone',
            field=models.CharField(max_length=10, null=True, verbose_name='Número de Teléfono'),
        ),
        migrations.AddField(
            model_name='polls',
            name='creator',
            field=models.CharField(default='Admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_text',
            field=models.CharField(max_length=300, null=True, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.questions', verbose_name='ID Pregunta'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='name',
            field=models.CharField(max_length=120, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_text',
            field=models.CharField(max_length=200, null=True, verbose_name='Pregunta'),
        ),
    ]
