# Generated by Django 3.1.2 on 2020-10-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201029_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='candidate',
            field=models.ManyToManyField(to='polls.Candidates', verbose_name='Candidato'),
        ),
    ]
