# Generated by Django 3.1.2 on 2020-10-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20201029_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='answers_id',
            field=models.ManyToManyField(to='polls.Answers'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='candidate',
            field=models.ManyToManyField(to='polls.Candidates'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='question_id',
            field=models.ManyToManyField(to='polls.Questions'),
        ),
    ]
