# Generated by Django 3.1.2 on 2020-10-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20201030_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='answers_id',
            field=models.ManyToManyField(null=True, to='polls.Answers'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='candidate',
            field=models.ManyToManyField(null=True, to='polls.Candidates'),
        ),
    ]
