# Generated by Django 3.1.2 on 2020-10-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20201031_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='answers_id',
            field=models.ManyToManyField(to='polls.Answers'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='candidate',
            field=models.ManyToManyField(to='polls.Candidates'),
        ),
    ]
