# Generated by Django 3.1.2 on 2020-11-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20201031_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='answers_id',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='question_id',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
