# Generated by Django 3.1.2 on 2020-11-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20201103_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='url_form',
            field=models.URLField(null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='creator',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='polls',
            name='email_creator',
            field=models.EmailField(max_length=254),
        ),
    ]
