# Generated by Django 3.1.2 on 2020-11-05 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20201103_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredPolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polls')),
            ],
            options={
                'verbose_name': 'Encuesta Respondida',
                'verbose_name_plural': 'Encuestas Respondidas',
            },
        ),
    ]
