# Generated by Django 3.1.2 on 2020-11-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_answeredpolls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeredpolls',
            name='poll_id',
        ),
    ]
